name: Manual Build
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: mod
          path: build/libs/*.jar
